### ISSUE TITLE
The fix for issue #15 is not released on Pypi

### ISSUE THREAD

**Issue by andy-maier** [agrover/python-kmod#17]
@grzn @agrover 

I ran into issue #15 and found that a fix for it is in the master branch of this repo, but that level has never been released to Pypi.

-> Could you please release it to Pypi?

Details about the issue:

* I had the issue on RHEL 7.3 on x86_64, with a virtual Python 2.7 environment with these packages:
```
$ pip list
pip (9.0.1)
setuptools (36.2.0)
wheel (0.29.0)
```
* Failed attempt to install kmod 0.9.1 from Pypi:
```
$ pip install kmod
Collecting kmod
  Using cached kmod-0.9.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-A4aKi4/kmod/setup.py", line 24, in <module>
        from Cython.Distutils import build_ext as _build_ext
    ImportError: No module named Cython.Distutils
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-A4aKi4/kmod/
```

**Comment by agrover** [comment]
python-kmod has been integrated into the main kmod development repo, so you should ask the main kmod developers.

**Comment by remingtonc** [comment]
@agrover What does that mean? Is there another package that should be used? Does it come OOB with Linux? Is this repo not a reflection of the PyPi package?

**Comment by agrover** [comment]
I've uploaded a 0.9.2 to pypi with the fix.
