### ISSUE TITLE
modeprode crashes because for some reason lookup does not work

### ISSUE THREAD

**Issue by oz123** [agrover/python-kmod#7]
Hi, 
I could not figure out how to use the lookup function. 

The documentation is not clear, nor the code of lookup itself. 

I tried the following:

```
In [1]: import kmod
In [2]: km = kmod.Kmod()

In [7]: km.lookup("tpacpi")
Out[7]: <kmod.kmod.__pyx_scope_struct_1_lookup at 0x14689f0>

In [8]: a=km.lookup("tpacpi")

In [9]: a.next()
Segmentation fault
```

I used 'tpacpi', because: 

```
root@yenitiny:/home/ozdeb# modinfo thinkpad_acpi | grep alias
alias:          dmi:bvnIBM:bvrI[MU]ET??WW*
alias:          tpacpi
alias:          acpi*:LEN0068:*
alias:          acpi*:IBM0068:*
```

But maybe I am wrong here, I didn't find any better way to find alias of a module.

Further tries also failed like this:

```
In [1]: import kmod

In [2]: km=kmod.Kmod()

In [3]: a=km.lookup("acpi*:IBM0068:*")

In [4]: a.next()
Segmentation fault
```

or ...

```
In [3]: km.lookup("acpi\*:IBM0068:\*")
Out[3]: <kmod.kmod.__pyx_scope_struct_1_lookup at 0x19409f0>

In [4]: a=km.lookup("acpi\*:IBM0068:\*")

In [5]: a.next()
Segmentation fault
```

oddly enough, this works:

```
  root@yenitiny:/home/ozdeb# modprobe -rv acpi\*:IBM0068:\*
  rmmod thinkpad_acpi
  rmmod nvram
  root@yenitiny:/home/ozdeb# modprobe -iv acpi\*:IBM0068:\*
  insmod /lib/modules/3.2.0-4-amd64/kernel/drivers/char/nvram.ko 
  insmod /lib/modules/3.2.0-4-amd64/kernel/drivers/platform/x86/thinkpad_acpi.ko fan_control=0 
```

So, I am quite puzzled here, whether it's me not understanding how to use km.lookup or that there is some issue.

**Comment by oz123** [comment]
as a temporary solution, I edited the function modprobe and disabled lookup:

```
   --- a/kmod/kmod.pyx.original
   +++ b/kmod/kmod.pyx.mine
   @@ -103,8 +103,9 @@ cdef class Kmod (object):
             yield (mod.name, mod.size)

       def modprobe(self, alias_name, *args, **kwargs):
  -        for mod in self.lookup(alias_name=alias_name):
  -            mod.insert(*args, **kwargs)
  +        #for mod in self.lookup(alias_name=alias_name):
  +       mod = self.module_from_name(name=alias_name) 
  +       mod.insert(*args, **kwargs)
```

and now this method can be used like this:

```
In [31]: km.rmmod("thinkpad_acpi")

In [32]: km.modprobe('thinkpad_acpi',**{'extra_options':'fan_control=1'})
```

I still don't get what are *args used for in the original code ... I could not find any way to use them. 
So it would be nice to see some examples of usage for the following methods of the class kmod:

```
def modprobe(self, alias_name, *args, **kwargs):
def rmmod(self, module_name, *args, **kwargs):
```

**Comment by agrover** [comment]
I tried your first example and it worked for me:

```
In [1]: import kmod

In [2]: km = kmod.Kmod()

In [3]: km.lookup("tpacpi")
Out[3]: <generator at 0x12ca938>

In [4]: km.lookup("tpacpi").next()
Out[4]: <kmod.module.Module at 0x7f2f80d55d50>

In [5]: km.lookup("tpacpi").next().name
Out[5]: u'thinkpad_acpi'
```

This is on Fedora 18 x86_64 with python-kmod-0.9-1 installed from rawhide repo (f19)

**Comment by oz123** [comment]
Hi Andy, thanks for the reply. I am adding the following info. Just tried again your snippet:

```
In [3]: import kmod

In [4]: km = kmod.Kmod()
In [5]: km.lookup("tpacpi")
Out[5]: <kmod.kmod.__pyx_scope_struct_1_lookup at 0x2f2d940>
In [6]: km.lookup("tpacpi").next()
Segmentation fault
ozdeb@yenitiny:~/Desktop/python-kmod$ uname -a
Linux yenitiny 3.2.0-4-amd64 #1 SMP Debian 3.2.35-2 x86_64 GNU/Linux
ozdeb@yenitiny:~/Desktop/python-kmod$ apt-cache show libkmod-dev
Package: libkmod-dev
Source: kmod
Version: 9-2
Installed-Size: 250
Maintainer: Marco d'Itri <md@linux.it>
Architecture: amd64
Depends: libkmod2 (= 9-2)
Description-en: libkmod development files
This package contains the files needed for developing applications that
use libkmod.
Multi-Arch: same
Description-md5: d05b96c5ea92d4587ad0abe33b518fb0
Tag: devel::library, role::devel-lib
```

   Section: libdevel

Maybe it is a problem one level lower (e.g. in Libkmod in Debian)...

**Comment by oz123** [comment]
Hi Andy, 
I just built kmod-5 and Cython 0.17.4 on CentOS6.3, together with python-kmod. Everython works fine. 
I'll have to conclude that it is a Debian problem. But if you want this package (I want too at least) to be in Debian, this
needs to be narrowed to down.

**Comment by agrover** [comment]
Yeah I'd like it on Debian too! :) Do you think Marco, the libkmod-dev maintainer, might be able to help?

**Comment by oz123** [comment]
Hi Andy, 
I can't answer for Marco :-) But ... I already did [packaged python-kmod](https://mentors.debian.net/package/python-kmod) and uploaded it to mentors.debian.net.
I am going to send an email to Marco, will put you on CC.

**Comment by oz123** [comment]
More info:
I Built the same version as in Fedora now (http://pkgs.fedoraproject.org/cgit/Cython.git/ -version 0.17.3 ) from upstream sources and kmod does not crash. Debian has version  0.17.2 in Experimental, so I will need to bump the dependencies of python-kmod to a higher version. 
Thanks for your feedback so far.

**Comment by agrover** [comment]
Interesting! Thanks for staying on top of this.
